[project]
name = "weather"
version = "0.1.0"
description = "Official MCP tutorial example"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
